export const ADD_MESSAGE = 'ADD_MESSAGE'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
export const ADD_USER = 'ADD_USER'
export const USERS_LIST = 'USERS_LIST'
export const SET_USERNAME = 'SET_USERNAME'
export const ADD_ROOM = 'ADD_ROOM'
export const ROOM_ADDED = 'ROOM_ADDED'
export const ROOMS_LIST = 'ROOMS_LIST'
